<?php
$dbconfig=array();
$dbconfig['type']="postgres";
$dbconfig['db']="grant_management_tool";
$dbconfig['host']="localhost";
$dbconfig['port']="5432";
$dbconfig['username']="postgres";
$dbconfig['pw']="ae3f65g";
?>
